Hospital model
BenMukebo/health-care-online-system pull request #10
Opened 2023-04-07 20:34 UTC by Alfredbis29

2023-04-10 14:33 UTC, Tresor11 requested changes

2023-04-10 14:33 UTC, Tresor11 commented on Procfile.dev
> -css: bin/rails tailwindcss:watch
Why did you change this?

2023-04-10 14:33 UTC, Tresor11 commented on app/models/hospital.rb
> +  belongs_to :user
We do not need the associations here
You should just create the hospital model with a name and address attribute

2023-04-10 14:33 UTC, Tresor11 commented on config/database.yml
> +  password: alfred
Remove this please

2023-04-10 14:33 UTC, Tresor11 commented on config/database.yml
> +  password: alfred
Remove this as well

2023-04-10 14:33 UTC, Tresor11 commented on Gemfile
> +ruby '3.0.1'
Don't change the ruby version

2023-04-10 14:33 UTC, Tresor11 commented on Gemfile
> +gem 'sidekiq'
Why re you setting up sidekiq?

2023-04-11 22:14 UTC, BenMukebo commented on app/controllers/hospitals_controller.rb
> +  end
- [ ] Kindly make sure to correctly set up the hospital_params for the Jsonb records. Columns which has jsonb type are expected to contain a different type of information (int, string, array, ...) you need to find all the necessary information related o the hospital.
- For example, the address of the hospital may have country, city, and state. .....

```ruby
{ address: %i[country city state zip_code] }
```

2023-04-15 18:58 UTC, Tresor11 approved these changes

2023-04-15 21:57 UTC, BenMukebo commented on app/controllers/hospitals_controller.rb
> +  end
Hello @Tresor11, As suggested here, I made some pushes. Please check them out and tell me what are missing ?

2023-04-17 10:14 UTC, BenMukebo commented
@Tresor11, Still waiting for review here as weel !!

2023-04-18 08:47 UTC, merged